Home page
sam9111/ssn-acm-w pull request #15
Opened 2021-08-16 19:59 UTC by sam9111

2021-08-16 20:03 UTC, sam9111 commented
Weird A in the Heading

2021-08-17 04:20 UTC, harisarang commented on src/pages/index.js
> +  Button,
Remove unused components

2021-08-17 04:32 UTC, harisarang commented on src/pages/index.js
> +        <Flex
Since, this component is used more than once you seprate it as some card component

2021-08-17 04:34 UTC, harisarang requested changes
Other than these everything LGTM

2021-08-17 05:51 UTC, merged