Blog draft
sam9111/ssn-acm-w pull request #18
Opened 2021-08-18 08:48 UTC by ramumaha

The blog background doesn't seem to extend through the page when we add the card components to it.As I have used the same card component for both blog and events the changes are reflected in both.Is it fine or do you want me to create a new component for each?

2021-08-18 09:53 UTC, harisarang commented on src/pages/2020_2021.js
> +              bgSize="contain"
Duplicate props here

2021-08-18 09:54 UTC, harisarang commented on src/pages/2020_2021.js
> +              bgSize="contain"
Duplicate props here

2021-08-18 09:55 UTC, harisarang commented on src/pages/blog.js
> +import { Container, Stack, Box, Heading, Text, Img } from "@chakra-ui/react";
Unused imports

2021-08-18 09:59 UTC, harisarang commented on src/pages/past.js
> +          //  bg={useColorModeValue("white", "gray.900")}
If the comments are not going to be used it can be removed

2021-08-18 10:05 UTC, harisarang commented on src/pages/past.js
> +              bgSize="contain"
Look what I hvae found 🧐. Duplicate props 😆

2021-08-18 10:07 UTC, harisarang commented on src/pages/upcoming.js
> +import { Box, Button, Flex } from "@chakra-ui/react";
Remove unused components

2021-08-18 10:08 UTC, harisarang requested changes
Make sure not have duplicate props

2021-08-18 10:10 UTC, harisarang commented on src/pages/past.js
> +import { render } from "react-dom";
Remove unused components

2021-08-18 10:37 UTC, ramumaha commented on src/pages/blog.js
> +import { Container, Stack, Box, Heading, Text, Img } from "@chakra-ui/react";
Removed

2021-08-18 10:38 UTC, ramumaha commented on src/pages/upcoming.js
> +import { Box, Button, Flex } from "@chakra-ui/react";
removed

2021-08-22 15:55 UTC, harisarang approved these changes

2021-08-22 16:02 UTC, merged